badge: Limited Beta Release
title: The issue tracking tool you'll enjoy using
description: Waitlist.do helps streamline software projects, sprints, tasks, and bug tracking. It's built for high-performance teams.
label: enter your work email
callToAction: Request Early Access
